default_language_version:
  python: python3.10
exclude: 'ccmlops/|tsconfig.json'  # tsconfig breaks json pre-commit hook
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [ "--max-line-length", "140","--per-file-ignores" ,"__init__.py:F401, plots.py:C901", "--extend-ignore", "E203" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies: [ tokenize-rt==3.2.0,types-PyYAML, types-all ] # , pandas-stubs
  #        args: ["--check-untyped-defs"]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      #      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-json
        types: [json]
      - id: check-toml
        types: [toml]
      - id: pretty-format-json
        args: ["--autofix"]
      - id: name-tests-test
  #        args: ["--pytest-test-first"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'  # or any later Vulture version
    hooks:
      - id: vulture
        args: [ "src", "--min-confidence", "61" ]

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        exclude: ^tests/
#  -   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#      rev: v1.3.1
#      hooks:
#      -   id: python-safety-dependencies-check
#          files: 'requirements.txt'
